# Generated by Django 5.1 on 2024-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
