# Generated by Django 5.1 on 2024-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_blog_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="category",
            new_name="tags",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
