# Generated by Django 5.1 on 2024-11-03 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0004_category_alter_blog_id_alter_blog_slug_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
    ]
