# Generated by Django 5.1 on 2024-11-13 18:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0006_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
